build wgschirm:
  image: node:latest
  stage: build
  script:
    - cd dashboard
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - dashboard/dist
    expire_in: 1 hour
  only:
    - master
  cache:
    paths:
      - dashboard/node_modules/

deploy wgschirm:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # deploy dashboard
    - rsync -rav --delete dashboard/dist/ gitlab@iamjonathan.de:/var/www/wgschirm/dashboard/
    # deploy server
    - ssh gitlab@iamjonathan.de "pm2 delete -s wgschirm || :"
    - rsync -rav --exclude='.gitignore' --exclude='old_modules/' --delete-excluded server/ gitlab@iamjonathan.de:/var/www/wgschirm/server/
    - ssh gitlab@iamjonathan.de "cd /var/www/wgschirm/server/ && npm install"
    - ssh gitlab@iamjonathan.de "cd /var/www/wgschirm/server/ && pm2 start ecosystem.config.js"
  only:
    - master
